name: Measure Code Coverage

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Install coverlet.msbuild in BO4ETestProject
        run: cd BO4ETestProject && dotnet add package coverlet.msbuild
      - name: Install coverlet.msbuild in TestBO4E-dotnet-Encryption
        run: cd TestBO4E-dotnet-Encryption && dotnet add package coverlet.msbuild
      - name: Install coverlet.msbuild in TestBO4E-dotnet-Extensions
        run: cd TestBO4E-dotnet-Extensions && dotnet add package coverlet.msbuild
      - name: Install coverlet.msbuild in TestBO4E-dotnet-Reporting
        run: cd TestBO4E-dotnet-Reporting && dotnet add package coverlet.msbuild
      - name: Run Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --configuration Release
        # todo: maybe add the /p:Threshold=60 parameter
      - name: what is the filename
        run: ls
      - name: Enforce Min Coverage for BO4ETestProject
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "BO4ETestProject/TestResults/coverage.info"
          min_coverage: 55
      - name: Enforce Min Coverage for TestBO4E-dotnet-Encryption
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "TestBO4E-dotnet-Encryption/TestResults/coverage.info"
          min_coverage: 60
      - name: Enforce Min Coverage for TestBO4E-dotnet-Extensions
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "TestBO4E-dotnet-Extensions/TestResults/coverage.info"
          min_coverage: 60
      - name: Enforce Min Coverage for TestBO4E-dotnet-Reporting
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "TestBO4E-dotnet-Reporting/TestResults/coverage.info"
          min_coverage: 60