name: Run Unit Tests (BO4E) as Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.000
    - name: Run Tests  
      run: dotnet test --configuration Release
